# Generated by Django 2.2.5 on 2019-11-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('1', 'Пн'), ('2', 'Вт'), ('3', 'Ср'), ('4', 'Чт'), ('5', 'Пт'), ('6', 'Сб'), ('7', 'Вс'), ('1-5', 'Пн-Пт'), ('6,7', 'Сб-Вс'), ('8', 'Ежедневно')], max_length=50)),
                ('times', models.CharField(default='Круглосуточно', max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.CharField(max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('owner', models.CharField(blank=True, default='', max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
