# Generated by Django 2.2.5 on 2019-11-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(default='Ежедневно', max_length=50)),
                ('times', models.CharField(default='Круглосуточно', max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('value', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('value', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Office')),
            ],
        ),
    ]
