# Generated by Django 2.2.5 on 2019-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20191118_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('P', 'Телефон'), ('E', 'Email')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='days',
            field=models.CharField(choices=[('1', 'Пн'), ('2', 'Вт'), ('3', 'Ср'), ('4', 'Чт'), ('5', 'Пт'), ('6', 'Сб'), ('7', 'Вс'), ('1-5', 'Пн-Пт'), ('6,7', 'Сб-Вс'), ('8', 'Ежедневно')], max_length=50, verbose_name='Дни работы'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='times',
            field=models.CharField(default='Круглосуточно', max_length=50, verbose_name='Часы работы'),
        ),
    ]
