# Generated by Django 2.2.5 on 2019-11-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20191121_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Office', verbose_name='Оффис'),
        ),
    ]
