# Generated by Django 2.2.5 on 2019-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
