# Generated by Django 2.2.5 on 2019-11-18 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191108_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('text', models.TextField(blank=True, default='')),
                ('day', models.IntegerField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('db_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
