# Generated by Django 2.2.5 on 2019-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=50, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='day',
            field=models.IntegerField(blank=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Заголовок'),
        ),
    ]
