# Generated by Django 2.2.5 on 2019-11-20 17:12

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191120_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos', verbose_name='Главное фото'),
        ),
    ]
