# Generated by Django 2.2.5 on 2019-11-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191120_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
