# Generated by Django 2.2.5 on 2019-11-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='tour',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='logotip',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tours.TourType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toursection',
            name='day',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='toursection',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
