# Generated by Django 2.2.5 on 2019-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursbanner',
            options={'verbose_name': ''},
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='day',
            field=models.IntegerField(blank=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='info',
            field=models.TextField(blank=True, default='', verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='logotip',
            field=models.ImageField(null=True, upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='path',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Путь прохождения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='toursbanner',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='toursbanner',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='toursection',
            name='day',
            field=models.IntegerField(blank=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='toursection',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='toursection',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='toursection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='title',
            field=models.CharField(default='Тур', max_length=50, verbose_name='Заголовок'),
        ),
    ]
