# Generated by Django 2.2.5 on 2019-11-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20191119_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур'},
        ),
        migrations.AlterModelOptions(
            name='toursbanner',
            options={'verbose_name': 'Банер'},
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'verbose_name': 'Тип тура'},
        ),
    ]
