# Generated by Django 2.2.5 on 2019-11-20 16:10

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20191119_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='toursbanner',
            options={'verbose_name': 'Банер', 'verbose_name_plural': 'Банеры'},
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'verbose_name': 'Тип тура', 'verbose_name_plural': 'Типы туров'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AlterField(
            model_name='toursbanner',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
