# Generated by Django 2.2.5 on 2019-11-20 16:40

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20191120_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='photos', verbose_name='Главное фото'),
        ),
    ]
