# Generated by Django 2.2.5 on 2019-11-20 17:12

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20191120_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos', verbose_name='Главное фото'),
        ),
    ]
