# Generated by Django 2.2.5 on 2019-11-20 18:49

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20191120_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=None, upload_to='photos', verbose_name='Главное фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='toursbanner',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos', verbose_name='Главное фото'),
        ),
    ]
