# Generated by Django 2.2.5 on 2019-11-21 19:12

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20191120_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='logotip',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='', verbose_name='Логотип'),
        ),
    ]
