# Generated by Django 2.2.5 on 2019-11-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('value', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('value', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Office')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
