# Generated by Django 2.2.5 on 2019-11-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191106_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursbaner',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='subtitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='toursbaner',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
