# Generated by Django 2.2.5 on 2019-11-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191107_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesection',
            name='article',
        ),
        migrations.RemoveField(
            model_name='email',
            name='office',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='office',
        ),
        migrations.RemoveField(
            model_name='sheduleitem',
            name='office',
        ),
        migrations.RemoveField(
            model_name='toursection',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourtype',
            name='baner',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleSection',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='SheduleItem',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='ToursBaner',
        ),
        migrations.DeleteModel(
            name='TourSection',
        ),
        migrations.DeleteModel(
            name='TourType',
        ),
    ]
